### PR TITLE
scripts: Add capability to specify node and cpu_bind options

### PR DESCRIPTION
**Pull request by tonyzinger**
@sungeunchoi

### CODE REVIEW

**Comment by sungeunchoi** [comment]
This commit looks like it also changes PINGPONG_ARGS, though the commit message doesn't say that.  Is that intentional?  If so, does it make the pingpong tests do pretty much exactly what our ported tests do?

**Comment by tonyzinger** [comment]
The rdm_latency and rdm_latency_threaded tests use a warmup (skip) value of 1000 and number of transfers (loop) value of 10000.

Yes, I forgot to put these changes into my mod description.

**Comment by sungeunchoi** [comment]
Cool.  For future SW archaeology investigations, can you update just the commit message portion to include this info?

Also, can you do a --signoff on the commit?  Thx.

**Comment by tonyzinger** [comment]
I have added a comment about changing the default value for warmup and the number of transfers to by mod description.  Also, I have added the sign-off information.

**Comment by sungeunchoi** [comment]
👍

**Pull request merged**
